### PR TITLE
Add the Pulsate

### PR DESCRIPTION
**Pull request by m1sk9**
#### 1Password Teams URL
pulsate-project.1password.com

#### Project Name
Pulsate Project

#### Short Description
Pulsate is the next generation of faster and developer-friendly distributed SNS (and of course user-friendly). It is being developed with the goal of becoming a powerful alternative to existing distributed SNSs in the future.

#### Project Age
[6 months](https://github.com/pulsate-dev/pulsate/commit/6d9b1b1746f64378c86dc6590820165fc548e1df)

#### Number Of Core Contributors
4 

#### Project Website
[pulsate-dev/pulsate](https://github.com/pulsate-dev/pulsate)

#### Repository URL(s)
[pulsate-dev/pulsate](https://github.com/pulsate-dev/pulsate)

#### Latest Release URL(s)
Currently under development. (To be released by 2024).

#### License
Apache-2.0

#### Name
m1sk9 (Sho Sakuma)

#### Email
m1sk9@pulsate.dev

#### Project Role
Product Owner

#### Profile/Website
- [GitHub](https://github.com/m1sk9)
- [Website](https://m1sk9.dev)

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?

- [x] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hey @m1sk9, thanks for applying and apologies for the delay. In reviewing your application it doesn't appear the email provided is associated with the 1Password account you're applying with. Are you able to update your application to specify the correct email? Alternatively, if you cannot provide address publicly, please send us at an email: opensource@1password.com - Thanks!

**Comment by m1sk9** [comment]
@jodyheavener 
I'm sorry. I updated the email address field immediately.
`m1sk9@pulsate.dev` is the email address for my account.

**Comment by jodyheavener** [comment]
Thanks for updating, @m1sk9! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.

Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

**Comment by m1sk9** [comment]
> Thanks for updating, @m1sk9! I've gone ahead and applied the promotion to your account.
> 
> If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.
> 
> Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

@jodyheavener Thank you!

**Pull request merged**
